# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrtbox < Formula
  desc "Declarative OpenWrt — one YAML file, atomic apply, auto-rollback."
  homepage "https://github.com/itslavrov/wrtbox"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_darwin_amd64.tar.gz"
      sha256 "ad39382933e4773bcddaba4e3b696ac8f81189776504254b72069a15cad5581d"

      define_method(:install) do
        bin.install "wrtbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_darwin_arm64.tar.gz"
      sha256 "a98dae022697d97991f2b836e36f141c890e82406f308fec6c5f97ef79b89979"

      define_method(:install) do
        bin.install "wrtbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_linux_amd64.tar.gz"
      sha256 "f26b05942dae1762a5f1c52958c82392535d34a7fdcd27ddb63b6d0549cbc395"
      define_method(:install) do
        bin.install "wrtbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_linux_arm64.tar.gz"
      sha256 "6ae86cf6f28b6c9269923ec98081be55b14c6f91bf116275a5df1fc43bdb26a1"
      define_method(:install) do
        bin.install "wrtbox"
      end
    end
  end

  test do
    system "#{bin}/wrtbox", "--version"
  end
end
