# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrtbox < Formula
  desc "Declarative OpenWrt — one YAML file, atomic apply, auto-rollback."
  homepage "https://github.com/itslavrov/wrtbox"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_darwin_amd64.tar.gz"
      sha256 "d38b5abe695ef3da6e0759dde001a7fbcda67c511a5b3f3827e2be60cdbf9fe8"

      define_method(:install) do
        bin.install "wrtbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_darwin_arm64.tar.gz"
      sha256 "771100bb812477f7155570d5a5a7003c73511c4887cc611ed06d7c6cb6b794a4"

      define_method(:install) do
        bin.install "wrtbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_linux_amd64.tar.gz"
      sha256 "f7b46a3e7dd0906edb66491d807ae5e48c7d502c78c62c2295911747750d099c"
      define_method(:install) do
        bin.install "wrtbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_linux_arm64.tar.gz"
      sha256 "d598c71c9be59e748bb2cda40175fdd6f69a0187742c010a33aa23bf8d1d4339"
      define_method(:install) do
        bin.install "wrtbox"
      end
    end
  end

  test do
    system "#{bin}/wrtbox", "--version"
  end
end
