# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wrtbox < Formula
  desc "Declarative OpenWrt — one YAML file, atomic apply, auto-rollback."
  homepage "https://github.com/itslavrov/wrtbox"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_darwin_amd64.tar.gz"
      sha256 "cd5d173c0d929c8e13609deec6c71478b57eda5084264ab17a57dde624e316cd"

      define_method(:install) do
        bin.install "wrtbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_darwin_arm64.tar.gz"
      sha256 "c4afcb828afecafa06b6d2b5c1ef09af9c5aa7dca99028029baece2eb4141e4b"

      define_method(:install) do
        bin.install "wrtbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_linux_amd64.tar.gz"
      sha256 "fe8ee5854ed81fe8882de9c2ae9186f9d1efcce1816f1aab6f171f1c785f4297"
      define_method(:install) do
        bin.install "wrtbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itslavrov/wrtbox/releases/download/v0.3.0/wrtbox_0.3.0_linux_arm64.tar.gz"
      sha256 "faa0f1d234f9125f04319462ab4b58d19c2a82a10f5e7b52e0bdc04656d8922d"
      define_method(:install) do
        bin.install "wrtbox"
      end
    end
  end

  test do
    system "#{bin}/wrtbox", "--version"
  end
end
